version: '3.8'

services:

  backend:
    build:
      context: ./tfm-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./tfm-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend