services:

  backend:
    build:
      context: ./tfm-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - net

  frontend:
    build:
      context: ./tfm-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - net
    depends_on:
      - backend
  
networks:
  net:
    driver: bridge